# cloudbuild.yaml
steps:
  - name: node
    entrypoint: npm
    args: ["install"]
  - name: node
    entrypoint: npm
    args: ["run", "build"]
  - name: "gcr.io/cloud-builders/docker"
    args: ['build', '-t', 
          'gcr.io/$PROJECT_ID/copasvioni:${SHORT_SHA}', '.']
  - name: "gcr.io/cloud-builders/docker"
    args: ['push', 'gcr.io/$PROJECT_ID/copasvioni:${SHORT_SHA}']
  # Deploy to Cloud Run
  - name: google/cloud-sdk
    args: ['gcloud', 'run', 'deploy', 'copasvioni', 
          '--image=gcr.io/$PROJECT_ID/copasvioni:${SHORT_SHA}', 
          '--region', 'asia-southeast2']
# timeout: "1600s"
images:
- 'gcr.io/$PROJECT_ID/copasvioni:${SHORT_SHA}'